Endpoint to delete categories.
alkemyTech/OT220-Server pull request #13
Opened 2022-05-23 21:57 UTC by ferdox2

https://alkemy-labs.atlassian.net/browse/OT220-44

Endpoint to delete categories.

2022-06-06 01:45 UTC, FernandoCiballero commented on app/controllers/categories_controller.rb
> +    category = Category.find(params[:id])
Sería mejor generar un método `set_category` y agregar el `before_action, :set_category, only: [destroy]`

2022-06-06 01:46 UTC, FernandoCiballero requested changes
Muy Bueno Luis!!! te dejo unos comentarios.

2022-06-06 18:40 UTC, ferdox2 commented on app/controllers/categories_controller.rb
> +    category = Category.find(params[:id])
Hecho

2022-06-13 03:18 UTC, FernandoCiballero approved these changes
Buen trabajo Luis!!! 👏

2022-06-13 03:23 UTC, merged