feat OT220-40: add endpoint for list categories
alkemyTech/OT220-Server pull request #21
Opened 2022-05-30 17:37 UTC by danielidr

Agregue endpoint para obtener la lista de las categorías.

2022-06-06 02:42 UTC, FernandoCiballero commented on app/controllers/categories_controller.rb
> +    @categories = Category.all
Recuerda que al estar implementado un soft delete, deberás listar solo las que nos fueron borradas.
https://github.com/jhawthorn/discard#discard-a-record

2022-06-06 02:43 UTC, FernandoCiballero commented on app/controllers/categories_controller.rb
> +    render json: @categories.to_json(only: ['name'])
Te sugiero revise como implementar el json utilizando [jbuilder](https://github.com/rails/jbuilder),

2022-06-06 02:45 UTC, FernandoCiballero commented on config/routes.rb
> +  get 'categories', to: 'categories#index'
en este caso sería mejor usar:
```suggestion
  resources :categories, only: %i[index]
```

2022-06-06 02:45 UTC, FernandoCiballero requested changes
Muy buen trabajo!! te dejo un par de comments.

2022-06-07 03:14 UTC, danielidr commented
> Muy buen trabajo!! te dejo un par de comments.

Modificado, muchas gracias

2022-06-13 03:44 UTC, merged