Feat/ot 220 17 model migration controller user
alkemyTech/OT220-Server pull request #3
Opened 2022-05-20 19:40 UTC by juakoloyu

First pull request for users :busts_in_silhouette:

2022-05-21 22:00 UTC, FernandoCiballero commented on db/migrate/20220520185715_create_users.rb
> +      t.string :email, null: false
Faltaría agregar la config para que los emails no se repitan en la base de datos.

2022-05-21 22:02 UTC, FernandoCiballero commented on app/models/user.rb
> +  belongs_to :role
Es una buena práctica que todas las restricciones de los campos de la base de datos esten acompañados de un validates en el modelo, por ejemplo:

```ruby
  validates :first_name, presence: true
```

2022-05-21 22:03 UTC, FernandoCiballero commented on db/migrate/20220520185715_create_users.rb
> +      t.string :firsName, null: false
A modo de convención de en Ruby on Rails, los nombres compuestos deben ir escritos en snake case:
```suggestion
      t.string :firsName, null: false
```
```suggestion
      t.string :first_name, null: false
```

2022-05-21 22:06 UTC, FernandoCiballero requested changes
Buen trabajo!! queda pendiente la foreign key en un archivo de migración aparte y las modificaciones comentadas.

2022-05-21 22:08 UTC, juakoloyu commented on db/migrate/20220520185715_create_users.rb
> +      t.string :email, null: false
Lo hice y otros cambios también, pero me rechaza el push de los nuevos cambios.

2022-05-21 22:12 UTC, ferdox2 commented on db/migrate/20220520185715_create_users.rb
> +      t.string :email, null: false
Necesitas hacer un git push --force-with-lease para que te deje pushear esos cambios

2022-05-21 22:20 UTC, juakoloyu commented on db/migrate/20220520185715_create_users.rb
> +      t.string :email, null: false
@ferdox2 :clap: gracias

2022-05-23 22:38 UTC, FernandoCiballero requested changes
Faltaría verificar con `bundle exec rubocop` y ya estaría listo.

2022-05-25 00:38 UTC, juakoloyu commented
En este PR quedaron algunas alertas de rubocop del tipo ya que fueron fixeadas en el otro PR:
# frozen_string_literal: true

2022-05-30 01:07 UTC, FernandoCiballero approved these changes

2022-05-30 01:25 UTC, merged