Feat/docker config files
alkemyTech/OT220-Server pull request #4
Opened 2022-05-20 22:09 UTC by juakoloyu

Este cambio contiene los archivos necesarios para trabajar con docker :whale2: 
- Dockerfile
- docker-compose
- Dos archivos database_example.yml de ejemplo: Uno para trabajar normalmente sin docker y el otro con docker.

También se agregó al gitignore el database.yml

2022-05-20 22:10 UTC, juakoloyu commented
@FernandoCiballero Parece que sigo teniendo un problema con el historial de commits

2022-05-21 21:56 UTC, FernandoCiballero commented on Dockerfile
> +EXPOSE 3000
Estaría bueno configurar tu editor de código para que quede una linea extra automáticamente al final del archivo. Te paso un ejemplo con VS Code: https://stackoverflow.com/questions/44704968/visual-studio-code-insert-newline-at-the-end-of-files

2022-05-21 21:58 UTC, FernandoCiballero commented on docker-compose.yml
> +  db-data:
Idem a lo anterior.

2022-05-21 21:58 UTC, FernandoCiballero requested changes
Por mi parte lo veo bien!!! fataría retocar un par de detalles de la configuración y ya estaría listo.

2022-05-23 21:19 UTC, merged