feat OT220-16 add: model migration and controller roles
alkemyTech/OT220-Server pull request #6
Opened 2022-05-21 15:37 UTC by danielidr

OT220-16 Adding model, migration and controller for roles

2022-05-21 22:30 UTC, FernandoCiballero commented on db/migrate/20220519225648_create_roles.rb
> +      t.string :name
Es una buena práctica agregar la validación tanto en el modelo como en el base de datos. Por ejemplo:
```suggestion
      t.string :name, null: false
```
Que se correspondería con el `validates :name, presence: true`

2022-05-21 22:32 UTC, FernandoCiballero commented on app/models/role.rb
> +    validates :name, presence: true
Deberías configurar la tabulación en tu editor de código a 2 espacios en vez de 4:
```suggestion
  validates :name, presence: true
```

2022-05-21 22:33 UTC, FernandoCiballero commented on app/models/role.rb
> +end
Deberías configurar para que se agregue una linea adicional al final del archivo. te paso un ejemplo para configurar en VS Code:
https://stackoverflow.com/questions/44704968/visual-studio-code-insert-newline-at-the-end-of-files

2022-05-21 22:34 UTC, FernandoCiballero requested changes
Muy buen trabajo Danielid!! te dejo unos comentarios.

2022-05-22 16:50 UTC, ruizender approved these changes

2022-05-22 23:05 UTC, FernandoCiballero approved these changes
Genial Danielid!!! 👏

2022-05-23 22:42 UTC, FernandoCiballero requested changes
Muy bien Danielid!!! una que corrijas la syntax con `bundle exec rubocop` quedaría listo.

2022-05-26 03:15 UTC, FernandoCiballero approved these changes

2022-05-26 03:22 UTC, merged