add model migration and controller categories OT220-18
alkemyTech/OT220-Server pull request #7
Opened 2022-05-21 17:31 UTC by mliedo05

Crear modelo, migración y controlador base de Categories.

modifique el modelo de category para que el campo name no sea Null con un validate

agregue la gema discard para trabajar softdeletes.
agregue la gema image_processing', '>= 1.2' para trabajar con active_storage

2022-05-21 20:20 UTC, ruizender approved these changes

2022-05-21 22:35 UTC, FernandoCiballero commented on Gemfile
> +gem 'image_processing', '>= 1.2'
La gema `image_processing` es solo necesaria en caso especiales. La deberías eliminar por el momento.

2022-05-21 22:37 UTC, FernandoCiballero commented on Gemfile
> +gem 'discard', '~> 1.2'
Esta gema deberías agregarla en la linea 11 debajo de bootsnap, en el mismo formato de las demas:
```suggestion
gem 'discard', '~> 1.2' # https://rubygems.org /gems/discard
```

2022-05-21 22:40 UTC, FernandoCiballero commented on db/migrate/20220521164701_create_categories.rb
> +      t.string :name
Por convenciones de RoR es buena práctica tener la restrición tanto en la base de datos como en el modelo.
```suggestion
      t.string :name, null: false
```

2022-05-21 22:41 UTC, FernandoCiballero requested changes
Muy bien Miguel!!! te dejo un par de comentarios.

2022-05-22 16:53 UTC, danielidr approved these changes

2022-05-23 22:43 UTC, FernandoCiballero commented on Gemfile
> +
Esta linea deberías eliminarla.
```suggestion
```

2022-05-26 03:23 UTC, FernandoCiballero approved these changes

2022-05-26 03:31 UTC, merged