add model migration and controller testimonials OT-220-20
alkemyTech/OT220-Server pull request #8
Opened 2022-05-21 20:30 UTC by ruizender

Add controller and model. Run migration for created table testimonials.

2022-05-21 20:30 UTC, ruizender commented
feat/OT220-20-add-model-migration-controllerr-testimonials

2022-05-21 22:42 UTC, FernandoCiballero commented on Gemfile
> +gem "image_processing", ">= 1.2"
La gema `image_processing` no es requerida para que funcione `active storage`. Deberías eliminarla por el momento.

2022-05-21 22:44 UTC, FernandoCiballero commented on Gemfile
> +gem 'discard', '~> 1.2'
Esta gema la podías ubicar en la linea 11 (debajo de bootsnap) para respetar el orden alfabético. En el formato sugerido:
```suggestion
gem 'discard', '~> 1.2' # https://rubygems.org /gems/discard
```

2022-05-21 22:46 UTC, FernandoCiballero commented on db/migrate/20220521183248_create_testimonials.rb
> +      t.string :name
Es buena práctica en RoR que las restricciones estén presentes tanto en el modelo con el la base de datos:
```suggestion
      t.string :name, null: false
```

2022-05-21 22:47 UTC, FernandoCiballero requested changes
Muy bueno Ender!! te dejo un par de comentarios.

2022-05-22 16:52 UTC, danielidr approved these changes

2022-05-22 22:58 UTC, FernandoCiballero commented on Gemfile
> +gem 'discard', '~> 1.2'
Falto la ruta con el link a rubygems de la gema y ya estaría listo.
```suggestion
gem 'discard', '~> 1.2' # gem 'discard', '~> 1.2', '>= 1.2.1'
```

2022-05-22 23:00 UTC, FernandoCiballero requested changes
Te dejé un comment más por el gemfile y quedaría corregir la migración.

2022-05-22 23:10 UTC, mliedo05 approved these changes

2022-05-26 12:14 UTC, FernandoCiballero commented on .gitignore
> -/config/database.yml
este archivo debería estar ignorado. ya que en ahora cada uno crea el archivo segun su configuración personalizada.

2022-05-30 01:33 UTC, merged